module Import

open System
open Microsoft.Office.Interop.Excel
open Preflop

let importRuleFromExcel fileName =
  let xlApp = new ApplicationClass()
  let xlWorkBook = xlApp.Workbooks.Open(fileName)
  let getCellValue (sheet : Worksheet) (name : string) = 
    let result = sheet.Cells.Range(name, name).Value2 :?> string
    if result = null then "" else result

  let xlWorkSheet12 = xlWorkBook.Worksheets.["12BB"] :?> Worksheet
  let getCellValue12BB name = 
    getCellValue xlWorkSheet12 name

  let xlWorkSheet25 = xlWorkBook.Worksheets.["25BB"] :?> Worksheet
  let getCellValue25BB name = 
    getCellValue xlWorkSheet25 name

  [|   { StackMin = 0
         StackMax = 12
         History = []
         Range = getCellValue12BB "C3"
         Action = Fold } 
       { StackMin = 0
         StackMax = 12
         History = []
         Range = getCellValue12BB "C1"
         Action = AllIn }
       { StackMin = 12
         StackMax = 25
         History = []
         Range = getCellValue25BB "F3"
         Action = Fold }
       { StackMin = 12
         StackMax = 25
         History = []
         Range = getCellValue25BB "F5"
         Action = Call }
       { StackMin = 12
         StackMax = 25
         History = []
         Range = getCellValue25BB "F12"
         Action = MinRaise }
       { StackMin = 12
         StackMax = 25
         History = []
         Range = getCellValue25BB "F37"
         Action = AllIn } 
       { StackMin = 0
         StackMax = 25
         History = [Limp; Raise (0, 3)]
         Range = getCellValue25BB "F7"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Limp; Raise (0, 3)]
         Range = getCellValue25BB "F8"
         Action = Call } 
       { StackMin = 0
         StackMax = 25
         History = [Limp; Raise (3, 100)]
         Range = getCellValue25BB "F5"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(0, 3)]
         Range = getCellValue25BB "F14"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(0, 3)]
         Range = getCellValue25BB "F15"
         Action = Call } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(0, 3)]
         Range = getCellValue25BB "F16"
         Action = MinRaise } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(0, 3)]
         Range = getCellValue25BB "F17"
         Action = AllIn }
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(3, 5)]
         Range = getCellValue25BB "F19"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(3, 5)]
         Range = getCellValue25BB "F20"
         Action = Call } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(3, 5)]
         Range = getCellValue25BB "F21"
         Action = MinRaise } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(3, 5)]
         Range = getCellValue25BB "F22"
         Action = AllIn } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(5, 7)]
         Range = getCellValue25BB "F24"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(5, 7)]
         Range = getCellValue25BB "F25"
         Action = Call } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(5, 7)]
         Range = getCellValue25BB "F26"
         Action = AllIn } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(7, 100)]
         Range = getCellValue25BB "F28"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); Raise(7, 100)]
         Range = getCellValue25BB "F29"
         Action = AllIn } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); RaiseAllIn]
         Range = getCellValue25BB "F31"
         Action = Fold } 
       { StackMin = 0
         StackMax = 25
         History = [Raise (0, 100); RaiseAllIn]
         Range = getCellValue25BB "F35"
         Action = Call } 
  |]