module Import

open System
open Microsoft.Office.Interop.Excel
open Preflop.Decide
open System.Runtime.InteropServices
open Excel
open Excel.Import

let fullRange = "22+,A2s+,K2s+,Q2s+,J2s+,T2s+,92s+,82s+,72s+,62s+,52s+,42s+,32s,A2o+,K2o+,Q2o+,J2o+,T2o+,92o+,82o+,72o+,62o+,52o+,42o+,32o"

let parseDouble (s: string) =
  let s2 = s.Replace(",", ".")
  System.Decimal.Parse(s2, System.Globalization.CultureInfo.InvariantCulture)

let getCellValue (sheet : Worksheet) (name : string) = 
  let result = sheet.Cells.Range(name, name).Value2 :?> string
  if result = null then "" else result

let getCellValues (sheet : Worksheet) (name1 : string) (name2 : string) = 
  Console.Write "."
  let result = sheet.Cells.Range(name1, name2).Value2 :?> Object[,]
  result 
    |> excelRangeToArray 
    |> Seq.map (fun x -> if x = null then "" else x.ToString())
    |> Array.ofSeq

let importRulesIP (xlWorkBook : IWorkbook) bb =
  let sheetName = bb.ToString() + "BB"
  let xlWorkSheet = xlWorkBook.GetWorksheet sheetName
  let sheetName = "IPInput -> " + sheetName + " -> "
  let cValues = xlWorkSheet.GetCellValues "C1" "C3"
  let fValues = xlWorkSheet.GetCellValues "F1" "F37"
  let getCellValueBB (name : string)= 
    let index = name.Substring(1) |> Int32.Parse
    if name.[0] = 'C' then cValues.[index - 1] else fValues.[index - 1]
  let range = (bb, bb)
  [|{ StackRange = range
      History = []
      Range = getCellValueBB "F3"
      Action = Fold
      Source = sheetName + "F3" }
    { StackRange = range
      History = []
      Range = getCellValueBB "F5"
      Action = Call
      Source = sheetName + "F5" }
    { StackRange = range
      History = []
      Range = getCellValueBB "F12"
      Action = MinRaise
      Source = sheetName + "F12" }
    { StackRange = range
      History = []
      Range = getCellValueBB "F37"
      Action = AllIn
      Source = sheetName + "F37" } 
    { StackRange = range
      History = [Limp; Raise (0m, 3m)]
      Range = getCellValueBB "F6"
      Action = Fold
      Source = sheetName + "F6" } 
    { StackRange = range
      History = [Limp; Raise (0m, 3m)]
      Range = getCellValueBB "F7"
      Action = Call
      Source = sheetName + "F7" } 
    { StackRange = range
      History = [Limp; Raise (0m, 3m)]
      Range = getCellValueBB "F8"
      Action = AllIn
      Source = sheetName + "F8" } 
    { StackRange = range
      History = [Limp; Raise (3m, 100m)]
      Range = getCellValueBB "F9"
      Action = AllIn
      Source = sheetName + "F9" } 
    { StackRange = range
      History = [Limp; Raise (3m, 100m)]
      Range = getCellValueBB "F5"
      Action = Fold
      Source = sheetName + "F5" } 
    { StackRange = range
      History = [Limp; RaiseAllIn]
      Range = getCellValueBB "F10"
      Action = Call
      Source = sheetName + "F10" } 
    { StackRange = range
      History = [Limp; RaiseAllIn]
      Range = getCellValueBB "F5"
      Action = Fold
      Source = sheetName + "F5" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(0m, 3.35m)]
      Range = getCellValueBB "F14"
      Action = Fold
      Source = sheetName + "F14" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(0m, 3.35m)]
      Range = getCellValueBB "F15"
      Action = Call
      Source = sheetName + "F15" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(0m, 3.35m)]
      Range = getCellValueBB "F16"
      Action = RaiseX 2.5m
      Source = sheetName + "F16" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(0m, 3.35m)]
      Range = getCellValueBB "F17"
      Action = AllIn
      Source = sheetName + "F17" }
    { StackRange = range
      History = [Raise (0m, 100m); Raise(3.35m, 5.05m)]
      Range = getCellValueBB "F19"
      Action = Fold
      Source = sheetName + "F19" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(3.35m, 5.05m)]
      Range = getCellValueBB "F20"
      Action = Call
      Source = sheetName + "F20" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(3.35m, 5.05m)]
      Range = getCellValueBB "F21"
      Action = RaiseX 2.5m
      Source = sheetName + "F21" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(3.35m, 5.05m)]
      Range = getCellValueBB "F22"
      Action = AllIn
      Source = sheetName + "F22" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(5.05m, 6.55m)]
      Range = getCellValueBB "F24"
      Action = Fold
      Source = sheetName + "F24" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(5.05m, 6.55m)]
      Range = getCellValueBB "F25"
      Action = Call
      Source = sheetName + "F25" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(5.05m, 6.55m)]
      Range = getCellValueBB "F26"
      Action = AllIn
      Source = sheetName + "F26" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(6.55m, 100m)]
      Range = getCellValueBB "F28"
      Action = Fold
      Source = sheetName + "F28" } 
    { StackRange = range
      History = [Raise (0m, 100m); Raise(6.55m, 100m)]
      Range = getCellValueBB "F29"
      Action = AllIn
      Source = sheetName + "F29" } 
    { StackRange = range
      History = [Raise (0m, 100m); RaiseAllIn]
      Range = getCellValueBB "F31"
      Action = Fold
      Source = sheetName + "F31" } 
    { StackRange = range
      History = [Raise (0m, 100m); RaiseAllIn]
      Range = getCellValueBB "F35"
      Action = Call
      Source = sheetName + "F35" } 
    |]

let importRulesOOP (xlWorkBook : IWorkbook) bb =
  let sheetName = bb.ToString() + "BB"
  let xlWorkSheet = xlWorkBook.GetWorksheet sheetName
  let sheetName = "OOPInput -> " + sheetName + " -> "
  let gValues = xlWorkSheet.GetCellValues "G1" "G27"
  let getCellValueBB (name : string)= 
    let index = name.Substring(1) |> Int32.Parse
    gValues.[index - 1]
  let getCellValuesBB names = 
    String.Join(",", names 
                     |> Seq.map (fun name -> (getCellValueBB name).Replace(" ", "")) 
                     |> Seq.filter (fun x -> x <> ""))
  let range = (bb, bb)
  if bb <= 7 then
     [| { StackRange = range
          History = [Limp]
          Range = getCellValueBB "G3"
          Action = Check
          Source = sheetName + "G3" } 
        { StackRange = range
          History = [Limp]
          Range = getCellValuesBB ["G4";"G5";"G6";"G7";"G8";"G9"]
          Action = RaiseX 3m
          Source = sheetName + "G4-G9" } 
        { StackRange = range
          History = [Limp]
          Range = getCellValueBB "G10"
          Action = AllIn
          Source = sheetName + "G10" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G5"
          Action = Fold
          Source = sheetName + "G5" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G6"
          Action = Call
          Source = sheetName + "G6" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G7"
          Action = AllIn
          Source = sheetName + "G7" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G8"
          Action = Fold
          Source = sheetName + "G8" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G9"
          Action = Call
          Source = sheetName + "G9" } 
        { StackRange = range
          History = [Raise(0m, 100m)]
          Range = getCellValueBB "G12"
          Action = Fold
          Source = sheetName + "G12" } 
        { StackRange = range
          History = [Raise(0m, 100m)]
          Range = getCellValueBB "G13"
          Action = Call          
          Source = sheetName + "G13" } 
        { StackRange = range
          History = [Raise(0m, 100m)]
          Range = getCellValueBB "G14"
          Action = RaiseX 2.5m
          Source = sheetName + "G14" } 
        { StackRange = range
          History = [Raise(0m, 100m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G15"
          Action = AllIn
          Source = sheetName + "G15" } 
        { StackRange = range
          History = [Raise(0m, 100m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G16"
          Action = Call
          Source = sheetName + "G16" } 
        { StackRange = range
          History = [Raise(0m, 100m)]
          Range = getCellValueBB "G17"
          Action = AllIn
          Source = sheetName + "G17" } 
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G19"
          Action = Fold
          Source = sheetName + "G19" }
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G20"
          Action = Call
          Source = sheetName + "G20" }
    |]
  else if bb = 15 then
     [| { StackRange = range
          History = [Limp]
          Range = getCellValueBB "G3"
          Action = Check
          Source = sheetName + "G3" } 
        { StackRange = range
          History = [Limp]
          Range = getCellValuesBB ["G4";"G5";"G6";"G7";"G8";"G9"]
          Action = RaiseX 3m
          Source = sheetName + "G4-G9" } 
        { StackRange = range
          History = [Limp]
          Range = getCellValueBB "G10"
          Action = AllIn
          Source = sheetName + "G10" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G5"
          Action = Fold
          Source = sheetName + "G5" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G6"
          Action = Call
          Source = sheetName + "G6" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G7"
          Action = AllIn
          Source = sheetName + "G7" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G8"
          Action = Fold
          Source = sheetName + "G8" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G9"
          Action = Call
          Source = sheetName + "G9" }    
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G19"
          Action = Fold
          Source = sheetName + "G19" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G20"
          Action = Call
          Source = sheetName + "G20" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G21"
          Action = RaiseX 2.5m
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G22"
          Action = AllIn
          Source = sheetName + "G22" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G21"
          Action = Fold
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G23"
          Action = Call
          Source = sheetName + "G23" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G21"
          Action = Fold
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G24"
          Action = AllIn
          Source = sheetName + "G24" }            
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G27"
          Action = Call
          Source = sheetName + "G27" }
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G26"
          Action = Fold
          Source = sheetName + "G26" }
    |]
  else if bb >= 16 then
    [|  { StackRange = range
          History = [Raise(2.5m, 4m)]
          Range = getCellValueBB "G19"
          Action = Fold
          Source = sheetName + "G19" } 
        { StackRange = range
          History = [Raise(2.5m, 4m)]
          Range = getCellValueBB "G20"
          Action = Call
          Source = sheetName + "G20" } 
        { StackRange = range
          History = [Raise(2.5m, 4m)]
          Range = getCellValueBB "G21"
          Action = RaiseX 2.5m
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 4m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G22"
          Action = AllIn
          Source = sheetName + "G22" } 
        { StackRange = range
          History = [Raise(2.5m, 4m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G21"
          Action = Fold
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 4m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G23"
          Action = Call
          Source = sheetName + "G23" } 
        { StackRange = range
          History = [Raise(2.5m, 4m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G21"
          Action = Fold
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 4m)]
          Range = getCellValueBB "G24"
          Action = AllIn
          Source = sheetName + "G24" } 
        { StackRange = range
          History = [Raise(4m, 100m)]
          Range = getCellValueBB "G27"
          Action = AllIn
          Source = sheetName + "G27" }
        { StackRange = range
          History = [Raise(4m, 100m)]
          Range = getCellValueBB "G26"
          Action = Fold
          Source = sheetName + "G26" }
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G27"
          Action = Call
          Source = sheetName + "G27" }
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G26"
          Action = Fold
          Source = sheetName + "G26" }
    |]
  else // 8 - 14
     [| { StackRange = range
          History = [Limp]
          Range = getCellValueBB "G3"
          Action = Check
          Source = sheetName + "G3" } 
        { StackRange = range
          History = [Limp]
          Range = getCellValuesBB ["G4";"G5";"G6";"G7";"G8";"G9"]
          Action = RaiseX 3m
          Source = sheetName + "G4-G9" } 
        { StackRange = range
          History = [Limp]
          Range = getCellValueBB "G10"
          Action = AllIn
          Source = sheetName + "G10" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G5"
          Action = Fold
          Source = sheetName + "G5" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G6"
          Action = Call
          Source = sheetName + "G6" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G7"
          Action = AllIn
          Source = sheetName + "G7" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G8"
          Action = Fold
          Source = sheetName + "G8" } 
        { StackRange = range
          History = [Limp; Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G9"
          Action = Call
          Source = sheetName + "G9" }     
        { StackRange = range
          History = [Raise(0m, 2.49999m)]
          Range = getCellValueBB "G12"
          Action = Fold
          Source = sheetName + "G12" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m)]
          Range = getCellValueBB "G13"
          Action = Call
          Source = sheetName + "G13" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m)]
          Range = getCellValueBB "G14"
          Action = RaiseX 2.5m
          Source = sheetName + "G14" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G15"
          Action = AllIn
          Source = sheetName + "G15" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G14"
          Action = Fold
          Source = sheetName + "G14" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G16"
          Action = Call
          Source = sheetName + "G16" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G14"
          Action = Fold
          Source = sheetName + "G14" } 
        { StackRange = range
          History = [Raise(0m, 2.49999m)]
          Range = getCellValueBB "G17"
          Action = AllIn
          Source = sheetName + "G17" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G19"
          Action = Fold
          Source = sheetName + "G19" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G20"
          Action = Call
          Source = sheetName + "G20" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G21"
          Action = RaiseX 2.5m
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G22"
          Action = AllIn
          Source = sheetName + "G22" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); Raise(0m, 100m)]
          Range = getCellValueBB "G21"
          Action = Fold
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G23"
          Action = Call
          Source = sheetName + "G23" } 
        { StackRange = range
          History = [Raise(2.5m, 100m); Raise(0m, 100m); RaiseAllIn]
          Range = getCellValueBB "G21"
          Action = Fold
          Source = sheetName + "G21" } 
        { StackRange = range
          History = [Raise(2.5m, 100m)]
          Range = getCellValueBB "G24"
          Action = AllIn
          Source = sheetName + "G24" } 
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G26"
          Action = Fold
          Source = sheetName + "G26" }
        { StackRange = range
          History = [RaiseAllIn]
          Range = getCellValueBB "G27"
          Action = Call
          Source = sheetName + "G27" }
      |]

let importRulesByStack importRules xlWorkBook =
  ([1..25]
  |> Seq.map (fun bb -> importRules xlWorkBook bb)
  |> Seq.collect id
  |> List.ofSeq)

type OopAdvancedRules = {
  Always: DecisionRule list
  LimpFoldLow: DecisionRule list
  LimpFoldBig: DecisionRule list
}

let importOopAdvanced (xlWorkBook : IWorkbook) =
  let xlWorkSheetLimpLow = xlWorkBook.GetWorksheet "limp fold low"
  let cellValuesLimpLow = xlWorkSheetLimpLow.GetCellValues "B3" "B16"
  let rangeLimp = (16, 25)

  let xlWorkSheetLimpBig = xlWorkBook.GetWorksheet "limp fold big"
  let cellValuesLimpBig = xlWorkSheetLimpBig.GetCellValues "B3" "B27"

  let xlWorkSheetRaise = xlWorkBook.GetWorksheet "preflop ranges vs minr"
  let cellValuesRaise = xlWorkSheetRaise.GetCellValues "B1" "B3"
  let rangeRaise = (15, 25)

  let xlWorkSheetCallingRange = xlWorkBook.GetWorksheet "EQ 3b shove - default, formula"
  let cellValuesCallingRange = xlWorkSheetCallingRange.GetCellValues "B12" "B16"

  { Always = Array.concat
              [|
                [0..4]
                |> Seq.map (fun i -> 
                  let r = [(23, 25); (20, 22); (18, 19); (16, 17); (14, 15)].[i]
                  let sheetName = sprintf "%i - %i bb" (snd r) (fst r)
                  let sheet = xlWorkBook.GetWorksheet sheetName
                  let cellValuesBbThresholds = sheet.GetCellValues "A1" "A37"
                  let cellValuesBbRanges = sheet.GetCellValues "B1" "B37"
                  [0..36]
                  |> Seq.map (fun row ->
                    { StackRange = r
                      History = [RaiseFor3BetShove(parseDouble cellValuesCallingRange.[i], parseDouble cellValuesBbThresholds.[row])]
                      Range = cellValuesBbRanges.[row]
                      Action = AllIn
                      Source = "PostflopPART2 -> " + sheetName + " -> B" + (i+1).ToString() })
                  |> Array.ofSeq)
                |> Array.concat;

                [|
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m)]
                   Range = cellValuesRaise.[0]
                   Action = RaiseX 2.5m
                   Source = "PostflopPART2 -> preflop ranges vs minr -> B1" }
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m); Raise(0m, 100m); Raise(0m, 100m)]
                   Range = cellValuesRaise.[0]
                   Action = AllIn
                   Source = "PostflopPART2 -> preflop ranges vs minr -> B1" }
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m); Raise(0m, 100m); RaiseAllIn]
                   Range = cellValuesRaise.[0]
                   Action = Call
                   Source = "PostflopPART2 -> preflop ranges vs minr -> B1" }
                 { StackRange = (20, 25)
                   History = [BluffableRaise]
                   Range = cellValuesRaise.[1]
                   Action = RaiseBluffX 2.5m
                   Source = "PostflopPART2 -> preflop ranges vs minr -> B2" }
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m)]
                   Range = cellValuesRaise.[2]
                   Action = Call
                   Source = "PostflopPART2 -> preflop ranges vs minr -> B3" }
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m)]
                   Range = fullRange
                   Action = Fold
                   Source = "PostflopPART2 -> preflop ranges vs minr" }
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m); Raise(0m, 100m); Raise(0m, 100m)]
                   Range = fullRange
                   Action = Fold
                   Source = "PostflopPART2 -> preflop ranges vs minr" }
                 { StackRange = rangeRaise
                   History = [Raise(0m, 2.5m); Raise(0m, 100m); RaiseAllIn]
                   Range = fullRange
                   Action = Fold
                   Source = "PostflopPART2 -> preflop ranges vs minr" }
                |]
              |]
            |> List.ofArray
    LimpFoldLow = 
              [ 
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpLow.[0]
                  Action = Check
                  Source = "PostflopPART2 -> limp fold low -> B3" };
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpLow.[1]
                  Action = RaiseX 3m
                  Source = "PostflopPART2 -> limp fold low -> B4"  };
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpLow.[2]
                  Action = AllIn
                  Source = "PostflopPART2 -> limp fold low -> B5"  } 
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
                  Range = cellValuesLimpLow.[8]
                  Action = AllIn
                  Source = "PostflopPART2 -> limp fold low -> B11"  }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseAllIn]
                  Range = cellValuesLimpLow.[9]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold low -> B12"  }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
                  Range = cellValuesLimpLow.[10]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold low -> B13"  }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(34)]
                  Range = cellValuesLimpLow.[11]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold low -> B14"  }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(30)]
                  Range = cellValuesLimpLow.[12]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold low -> B15"  }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(25)]
                  Range = cellValuesLimpLow.[13]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold low -> B16"  }
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = fullRange
                  Action = Fold
                  Source = "PostflopPART2 -> limp fold low"  }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
                  Range = fullRange
                  Action = Fold
                  Source = "PostflopPART2 -> limp fold low" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseAllIn]
                  Range = fullRange
                  Action = Fold
                  Source = "PostflopPART2 -> limp fold low" }
              ]
    LimpFoldBig = 
              [ 
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpBig.[0]
                  Action = Check
                  Source = "PostflopPART2 -> limp fold big -> B3" };
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpBig.[1]
                  Action = RaiseX 3m
                  Source = "PostflopPART2 -> limp fold big -> B4" };
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpBig.[2]
                  Action = RaiseBluffX 3m
                  Source = "PostflopPART2 -> limp fold big -> B5" };
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = cellValuesLimpBig.[3]
                  Action = AllIn
                  Source = "PostflopPART2 -> limp fold big -> B6" } 
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
                  Range = cellValuesLimpBig.[9]
                  Action = AllIn
                  Source = "PostflopPART2 -> limp fold big -> B12" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseAllIn]
                  Range = cellValuesLimpBig.[10]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B13" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
                  Range = cellValuesLimpBig.[11]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B14" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(34)]
                  Range = cellValuesLimpBig.[12]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B15" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(30)]
                  Range = cellValuesLimpBig.[13]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B16" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(25)]
                  Range = cellValuesLimpBig.[14]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B17" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(22)]
                  Range = cellValuesLimpBig.[15]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B18" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(30)]
                  Range = cellValuesLimpBig.[21]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B24" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(28)]
                  Range = cellValuesLimpBig.[22]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B25" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(25)]
                  Range = cellValuesLimpBig.[23]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B26" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseEQ(22)]
                  Range = cellValuesLimpBig.[24]
                  Action = Call
                  Source = "PostflopPART2 -> limp fold big -> B27" }
                { StackRange = rangeLimp
                  History = [Limp]
                  Range = fullRange
                  Action = Fold
                  Source = "PostflopPART2 -> limp fold big" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); Raise(0m, 100m)]
                  Range = fullRange
                  Action = Fold
                  Source = "PostflopPART2 -> limp fold big" }
                { StackRange = rangeLimp
                  History = [Limp; Raise(0m, 100m); RaiseAllIn]
                  Range = fullRange
                  Action = Fold
                  Source = "PostflopPART2 -> limp fold big" }
              ]
  }

let importHudData (xlWorkBook : IWorkbook) =
  let xlWorkSheet = xlWorkBook.GetWorksheet "Hud"
  [3..10000]
  |> Seq.map (fun row -> xlWorkSheet.GetCellValues ("A" + row.ToString()) ("E" + row.ToString()))
  |> Seq.takeWhile (fun vs -> not(String.IsNullOrEmpty(vs.[0])))
  |> Seq.map (fun vs ->  
     { VillainName = vs.[0] 
       OpenRaise20_25 = Int32.Parse(vs.[1]) 
       OpenRaise16_19 = Int32.Parse(vs.[2]) 
       OpenRaise14_15 = Int32.Parse(vs.[3])
       LimpFold = Int32.Parse(vs.[4]) }
     )
  |> List.ofSeq

let importRegs (xlWorkBook : IWorkbook) =
  let xlWorkSheet = xlWorkBook.GetWorksheet "regwar IP"
  xlWorkSheet.GetCellValues "A3" "A300"
  |> List.ofArray
  |> List.filter (String.IsNullOrEmpty >> not)

let importRegWarIPRanges (xlWorkBook : IWorkbook) regIndex stack =
  let xlWorkSheet = xlWorkBook.GetWorksheet "regwar IP"
  let row = regIndex + 3 |> string
  let column = excelColumns.[26 - stack]
  let cellValue = xlWorkSheet.GetCellValue (column + row)
  Ranges.parseRanges cellValue, "mfck beavers -> regwar IP -> " + column + row

let private importRegWarOOPRanges statsColumnIndex shoveColumnIndex k (xlWorkBook : IWorkbook) regIndex stack =
  let statsSheetName = sprintf "OOP %ibb stats" stack
  let xlWorkSheet = xlWorkBook.GetWorksheet statsSheetName
  let row = regIndex + 5 |> string
  let cellValues = xlWorkSheet.GetCellValues (excelColumns.[statsColumnIndex] + row) (excelColumns.[statsColumnIndex + 1] + row) |> Array.map parseDouble
  let BorD = cellValues.[0]
  let CorE = cellValues.[1]
  let TTP = stack * 2 |> decimal
  let threshold = (((-((((k+1m))*((100m-((100m*CorE)/BorD))/100m))))*(BorD/CorE)+((TTP/2m)-1m))*100m)/TTP
  
  let shoveSheetName = sprintf "OOP %ibb shove" stack
  let xlWorkSheet = xlWorkBook.GetWorksheet shoveSheetName
  let column = excelColumns.[1 + regIndex * 2 + shoveColumnIndex]
  let row = 3 + ((threshold - 26.5m) * 2m |> int)
  let row = max 3 (min 39 row) |> string

  let cellValue = xlWorkSheet.GetCellValue (column + row)
  Ranges.parseRanges cellValue, "mfck beavers -> " + shoveSheetName + " -> " + column + row

let importRegWarOOPLimpRanges xl regIndex stack = importRegWarOOPRanges 3 1 1m xl regIndex stack
let importRegWarOOPRaiseRanges xl regIndex stack = importRegWarOOPRanges 1 0 2m xl regIndex stack

let importRegWarOOPAIRanges (xlWorkBook : IWorkbook) regIndex stack =
  let sheetName = sprintf "OOP %ibb stats" stack
  let xlWorkSheet = xlWorkBook.GetWorksheet sheetName
  let row = regIndex + 5 |> string
  let cellValue = xlWorkSheet.GetCellValue ("H" + row)
  Ranges.parseRanges cellValue, "mfck beavers -> " + sheetName + " -> H" + row